// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var reactivemarkets = reactivemarkets || {};

/**
 * @const
 * @namespace
 */
reactivemarkets.papi = reactivemarkets.papi || {};

/**
 * @constructor
 */
reactivemarkets.papi.FeedRequestReject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reactivemarkets.papi.FeedRequestReject}
 */
reactivemarkets.papi.FeedRequestReject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reactivemarkets.papi.FeedRequestReject=} obj
 * @returns {reactivemarkets.papi.FeedRequestReject}
 */
reactivemarkets.papi.FeedRequestReject.getRootAsFeedRequestReject = function(bb, obj) {
  return (obj || new reactivemarkets.papi.FeedRequestReject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reactivemarkets.papi.FeedRequestReject=} obj
 * @returns {reactivemarkets.papi.FeedRequestReject}
 */
reactivemarkets.papi.FeedRequestReject.getSizePrefixedRootAsFeedRequestReject = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new reactivemarkets.papi.FeedRequestReject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reactivemarkets.papi.FeedRequestReject.prototype.reqId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
reactivemarkets.papi.FeedRequestReject.prototype.errorCode = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reactivemarkets.papi.FeedRequestReject.prototype.errorMessage = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reactivemarkets.papi.FeedRequestReject.startFeedRequestReject = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reqIdOffset
 */
reactivemarkets.papi.FeedRequestReject.addReqId = function(builder, reqIdOffset) {
  builder.addFieldOffset(0, reqIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} errorCode
 */
reactivemarkets.papi.FeedRequestReject.addErrorCode = function(builder, errorCode) {
  builder.addFieldInt32(1, errorCode, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} errorMessageOffset
 */
reactivemarkets.papi.FeedRequestReject.addErrorMessage = function(builder, errorMessageOffset) {
  builder.addFieldOffset(2, errorMessageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reactivemarkets.papi.FeedRequestReject.endFeedRequestReject = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reqIdOffset
 * @param {number} errorCode
 * @param {flatbuffers.Offset} errorMessageOffset
 * @returns {flatbuffers.Offset}
 */
reactivemarkets.papi.FeedRequestReject.createFeedRequestReject = function(builder, reqIdOffset, errorCode, errorMessageOffset) {
  reactivemarkets.papi.FeedRequestReject.startFeedRequestReject(builder);
  reactivemarkets.papi.FeedRequestReject.addReqId(builder, reqIdOffset);
  reactivemarkets.papi.FeedRequestReject.addErrorCode(builder, errorCode);
  reactivemarkets.papi.FeedRequestReject.addErrorMessage(builder, errorMessageOffset);
  return reactivemarkets.papi.FeedRequestReject.endFeedRequestReject(builder);
}

// Exports for Node.js and RequireJS
this.reactivemarkets = reactivemarkets;
